services:
  voicevox_bot:
    image: dqxtsubasa/voicevox_bot:latest
    container_name: voicevox_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data

  voicevox_engine:
    image: voicevox/voicevox_engine:latest
    container_name: voicevox_engine
    restart: unless-stopped
    ports:
      - "50021:50021"

volumes:
  sqlite_data:
